config/routes.rb
Sitespeed3::Application.routes.draw do
  get "dashboard/show"

  get "sessions/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"
  
  get "url/trends"

  
  match '/url/:id/trends',      :to => 'url#trends'
  match '/contact',     :to => 'pages#contact'
  match '/about',       :to => 'pages#about'
  match '/help',        :to => 'pages#help'
  match '/check_email', :to => 'users#check_email'
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/components/',  :to => 'yslow2#components'
  match 'yslow' => 'beacon#yslow'
  

  resources :users
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]
  resources :yslow2
  resources :url
  

  root :to => "pages#home"

end

app/views/shared/_error_messages.haml
- if object.errors.any?
  #error_explanation
    %h2
      = pluralize(object.errors.count, "error")
      prohibited this user from being saved:
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          = msg

app/views/shared/_feed.haml
- unless @feed_items.empty?
  %ul
    - @feed_items.each do |feed|
      %li
        = link_to gravatar_for(feed.user), feed.user
        = link_to feed.user.email, feed.user
        = link_to feed.content
        = "Posted {time_ago_in_words(feed.created_at)} ago"
        - if current_user?(feed.user)
          = link_to "delete", feed, :method => :delete, :confirm => "Are you sure?", :title => feed.content

app/views/shared/_micropost_form.haml
= form_for @micropost do |f|
  = render 'shared/error_messages', :object => f.object
  .field
    = f.text_area :content
  .actions
    = f.submit "Submit"
  

app/views/shared/_signin.haml
#signin
  %h2
    Sign In
  = form_for(:session, :url => sessions_path) do |f|
    .form_field 
      = f.label :email
      = f.text_field :email
    .form_field 
      = f.label :password
      = f.password_field :password
    .actions
      = f.submit "Sign In", :class => "button"
/ %p
/   New user?
/   = link_to "Sign up now!", signup_path

app/views/shared/_signup.haml
#signup
  %h2
    Sign Up
  = form_for @user do |f|
    = render 'shared/error_messages', :object => f.object
    .form_field    
      = f.label :email
      = f.text_field :email, :class => 'input', :tabindex => '1', :autocomplete => "OFF"
    .form_field
      = f.label :password
      = f.password_field :password, :class => 'input', :tabindex => '2'
    .form_field
      = f.label :password_confirmation, "Confirm"
      = f.password_field :password_confirmation, :class => 'input', :tabindex => '3'
    .actions
      = f.submit "Sign Up", :tabindex => '4', :class => "button"
  / %h3#ts
  /   Start tracking the front-end
  /   %br
  /     performance of your site.