config/routes.rb
Sitespeed3::Application.routes.draw do
  get "dashboard/show"

  get "sessions/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"
  
  get "url/trends"

  
  match '/url/:id/trends',      :to => 'url#trends'
  match '/contact',     :to => 'pages#contact'
  match '/about',       :to => 'pages#about'
  match '/help',        :to => 'pages#help'
  match '/check_email', :to => 'users#check_email'
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/components/',  :to => 'yslow2#components'
  match 'yslow' => 'beacon#yslow'
  

  resources :users
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]
  resources :yslow2
  resources :url
  

  root :to => "pages#home"

end

app/models/url.rb
class Url < ActiveRecord::Base
  has_many :yslows
  has_many :yslow2s
  has_many :page_speeds
  belongs_to :user
  
  def self.per_page
    50
  end
  
end

app/controllers/url_controller.rb
class UrlController < ApplicationController
  before_filter :signed_in_user,   :only => :destroy
  
  def index
    @title = "Measure Your App's Front-End Performance"
    @urls = Url.find(:all)    
  end

  def show
    @the_url = Url.find(params[:id])
    @yslow2s = current_user.urls.find_by_id(params[:id]).yslow2s.find(:all, :order => 'lt ASC')
  end
  
  def destroy
    Url.find(params[:id]).destroy
    flash[:success] = "Url deleted"
    redirect_to dashboard_show_path
  end
  
  def trends
    url_id = params[:id]
    @the_url = Url.find_by_id(url_id)
    @trends = get_trends
  end
  
  def get_trends
    record = params[:id]
    hash = Hash.new(0)
    yslow2s = Url.find_by_id(record).yslow2s
    yslow2s.each do |y|
      hash[y.created_at] = y.w
    end
    return hash.to_json 
  end
  
  private
  
    def signed_in_user
      redirect_to(signin_path) unless current_user
    end

end

app/helpers/url_helper.rb
module UrlHelper
  
  def load_time(milliseconds)
    milliseconds.to_f/1000

  end
  
  def readable_time_stamp(utc)
    time = Time.parse(utc)
    time.strftime("%B %d, %Y at %I:%M %p")
  end
  
  def url_display(url)
    url = Domainatrix.parse(url)
    display_url = "#{url.domain}.#{url.public_suffix }#{url.path}"
  end
  
  
  
end

app/views/url/index.html.haml
#sub_container
  #sub_container_back
    .module
      %table#dashboard
        %thead
          %th
            URL
          %th
            Load Time
          %th
            Empty Cache Page Weight
          %th
            Primed Cache Page Weight
          %th
            Empty Cache Requests
          %th
            Primed Cache Requests
          %th
            Stats
          %th
            Components
          %th
            YSlow Score
          %th
            Recorded Date
        %tbody
          - @urls.each do |u|
            %tr{:class=>"#{cycle('odd', 'even')} row"}
              %td.url      
                = link_to u.name, url_path(u)
              %td.load_time
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : (grade(u.yslow2s.find(:last).lt))
              %td.ec_pw
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : (grade(u.yslow2s.find(:last).w))
              %td.pc_pw
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : (grade(u.yslow2s.find(:last).w_c))
              %td.ec_r
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : (grade(u.yslow2s.find(:last).r))
              %td.pc_r
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : (grade(u.yslow2s.find(:last).r_c))
              %td.stats
                = link_to 'Show', all_components_path(u), :class => 'showDialog'
              %td.comps
                = link_to 'Components', all_components_path(u)
              %td.score
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : (grade(u.yslow2s.find(:last).o))
              %td.date
                = (u.yslow2s.find(:last) == nil) ? 'N/A' : u.yslow2s.find(:last).created_at.to_s(:short)
      #dialog.jqmWindow

app/views/url/show.html.haml
%nav#dashboard-nav
  %ul
    %li.active
      = link_to "History", dashboard_show_path
    %li
      = link_to "Trends", url_path + "/trends"
%section#beacon-data.module
  %h2
    / = "History for #{url_display(@the_url.name)}"
    = "History for #{@the_url.name}"
  %table#dashboard
    %thead
      %th
        Recorded Date
      %th
        Load Time
      %th
        Empty Cache Page Weight
      %th
        Primed Cache Page Weight
      %th
        Empty Cache Requests
      %th
        Primed Cache Requests
      %th
        YSlow Score
      %th
      %th
    %tbody
      - @yslow2s.each do |y|
        %tr{:class=>"#{cycle('odd', 'even')} row"}
          %td
            = readable_time_stamp(y.created_at.to_s)
          %td
            = load_time(y.lt)
          %td
            = number_to_human_size(y.w)
          %td
            = number_to_human_size(y.w_c)
          %td
            = y.r
          %td
            = y.r_c
          %td
            = y.o
          %td
            = link_to 'More', y, :class => 'showDialog button'
          

app/views/url/trends.html.haml
#trends
  = @the_url.name
  #chart
  #data
    = @trends