config/routes.rb
Sitespeed3::Application.routes.draw do
  get "dashboard/show"

  get "sessions/new"

  get "pages/home"

  get "pages/contact"

  get "pages/about"
  
  get "url/trends"

  
  match '/url/:id/trends',      :to => 'url#trends'
  match '/contact',     :to => 'pages#contact'
  match '/about',       :to => 'pages#about'
  match '/help',        :to => 'pages#help'
  match '/check_email', :to => 'users#check_email'
  match '/signup',      :to => 'users#new'
  match '/signin',      :to => 'sessions#new'
  match '/signout',     :to => 'sessions#destroy'
  match '/components/',  :to => 'yslow2#components'
  match 'yslow' => 'beacon#yslow'
  

  resources :users
  resources :sessions,    :only => [:new, :create, :destroy]
  resources :microposts,  :only => [:create, :destroy]
  resources :yslow2
  resources :url
  

  root :to => "pages#home"

end

app/views/layouts/_footer.haml
%footer
  .container
    %nav
      %ul
        %li.cr
          Copyright © 2010
          %a{:href => "http://www.fromthought2web.com"}
            From Thought 2 Web 
        %li.lnk
          = link_to "About", about_path
        %li.lnk
          = link_to "Contact", contact_path

app/views/layouts/_header.haml
%header
  %h1#logo
    - if current_user
      %a{:href => dashboard_show_path, :title => "highperformingsites.com"}
        HIGHPERFORMINGSITES.COM
    - else
      %a{:href => root_path, :title => "highperformingsites.com"}
        HIGHPERFORMINGSITES.COM
  %nav#main-nav
    - if signed_in?
      %ul
        %li.active
          = link_to "Dashboard", dashboard_show_path
        %li
          = link_to "Settings", edit_user_path(current_user)
        %li
          = link_to "Profile", current_user
        %li
          = link_to "All Users", users_path
        %li
          = link_to "Sign Out", signout_path, :method => :delete
    - else
      %ul
        %li
          = link_to "Sign In", signin_path
    / - else
    /   = render :partial => "shared/signin"

app/views/layouts/application.html.haml
!!! Strict
%html{ :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %title
      = title
    = csrf_meta_tag
    %meta{ :content => "text/html; charset=utf-8", "http-equiv" => "Content-Type" }
    = stylesheet_link_tag "blueprint/screen.css", "application.css", "jqmodal.css", "jquery.jqplot.min.css", :media => "screen, projection"
    = stylesheet_link_tag "blueprint/print.css", :media => "print"
    /[if lt IE 9]
      %script{:src => 'http://html5shim.googlecode.com/svn/trunk/html5.js'}
  %body
    = render :partial => 'layouts/header'
    .container
      #content_container
        #content
          - if flash[:warning] || flash[:notice] || flash[:success] || flash[:error]
            %section#flash.module
              %h2
                Status
              - flash.each do |key, value|
                %div{:class => "flash #{key}"}
                  = "#{value}"
          = yield
    = render :partial => 'layouts/footer'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js", :type => "text/javascript"}
    = javascript_include_tag "jqmodal", "jquery.validate.min", "jquery.bt.min", "https://www.google.com/jsapi", "google.charts", "application"
    /[if IE]
      = javascript_include_tag "excanvas.min.js"
    = render :partial => 'analytics/google_analytics'
    = debug(params) if Rails.env.development?